### ISSUE TITLE
能从一个点到另一个点吗

### ISSUE THREAD

**Issue by wanghepu** [ecojust/flyline#1]

**Comment by ecojust** [comment]
> _No description provided._
@wanghepu
`if(iPosition.x > end || iPosition.x < time){`
`//discard;`
`color = vec4(0.213,0.424,0.634,0.3);`
`}`


loadjson.html 的52,53行调整一下应该就能达到你要的效果。

**Comment by wanghepu** [comment]
是的，之前研究了一下，算是能实现了
import { ShaderMaterial, BufferGeometry, Points, AdditiveBlending, Color } from 'three'

const vertexShader = `
		   uniform float time;
    uniform float size;
    uniform float scale;
    varying float iOffset;
    varying float Psize;
    uniform float axes;
    uniform float invert;
    void main(){
        // iPosition = vec3(position);
        float pointsize = 1.;
        float offset = position.x;
        if(axes ==2.) {
            offset = position.y;
        }else if(axes ==3.) {
            offset = position.z;
        }
        iOffset = offset;
        if(invert == 1.) {
            if(offset < time && offset > (time - size)){
                pointsize =(time - offset) / size;
                // pointsize =offset;
            }
        }else {
            if(offset > time && offset < (time + size)){
                    pointsize = (offset - time) / size;
                }
        }
        gl_PointSize = pointsize* (pointsize+.3) * scale;
        Psize = pointsize;
        gl_Position = projectionMatrix * modelViewMatrix * vec4(position,1.0);
    }
		`
const fragmentShader = `
		 uniform float time;
    uniform float size;
    uniform vec3 colorf;
    uniform vec3 colort;
    varying float Psize;
    varying float iOffset;
    uniform float invert;
    varying vec2 vUv;
    vec3 stepColor(float offset) {
        float step = fract((offset - time)/size);
        float dr = abs(colort.x - colorf.x);
        float dg = abs(colort.y - colorf.y);
        float db = abs(colort.z - colorf.z);
        float r = colort.x > colorf.x?(dr*step+colorf.x):(colorf.x -dr*step);
        float g = colort.y > colorf.y?(dg*step+colorf.y):(colorf.y -dg*step);
        float b = colort.z > colorf.z?(db*step+colorf.z):(colorf.z -db*step);
        return vec3(r,g,b);
    }
    void main( void ) {
        float end;
        vec4 color;
        float offset = iOffset;
        if(invert == 1.) {
            end = time - size;
            if(offset<end || offset > time){
                discard;
            }else {
                color = vec4(stepColor(offset),Psize);
            }
        } else{
            end = time + size;
            if(offset> end || offset < time){
                discard;
            }else {
                color = vec4(stepColor(offset),Psize);
            }
        }
        float d = distance(gl_PointCoord, vec2(0.5, 0.5));
        if(abs(offset - end) < 0.2 || abs(offset- time) < 0.2){
            if(d > 0.5){
                discard;
            }
        }
        gl_FragColor = color;
        

    }`

// 飞线
export class FlyLinePoint {
  material
  pointMesh
  endPoint

  constructor(points, uniforms, params) {
    const uniformsTemp = {
      time: { value: -7 },
      size: { type: 'f', value: 15.0 },
      axes: { type: 'f', value: 1 },
      invert: { type: 'f', value: 0 },
      scale: { type: 'f', value: 3 },
      colorf: { type: 'c', value: new Color(0xffffff) },
      colort: { type: 'c', value: new Color(0xffffff) },
    }
    this.state = true
    this.max = 0
    this.min = 0
    this.points = points
    this.initAxes(uniformsTemp)
    this.uniforms = {
      ...uniformsTemp,
      ...uniforms,
    }
    this.speed = 1
    this.loop = 1
    if (params) {
      this.speed = params.speed
      this.loop = params.loop
      this.afterDispose = params.afterDispose
    }
    if (this.speed === undefined) {
      this.speed = 0.5
    }
    if (this.loop === undefined) {
      this.loop = 1
    }
    this.material = this.initMaterial()
    this.initPointMesh()
  }

  initAxes(uniforms) {
    const start = this.points[0]
    const end = this.points[this.points.length - 1]
    let invert = 0
    let axes = 1
    const xDis = Math.abs(end.x - start.x)
    const yDis = Math.abs(end.y - start.y)
    const zDis = Math.abs(end.z - start.z)
    if (xDis > yDis && xDis > zDis) {
      this.min = start.x
      this.max = end.x
    } else if (yDis > xDis && yDis > zDis) {
      axes = 2
      this.max = end.y
      this.min = start.y
    } else {
      axes = 3
      this.max = end.z
      this.min = start.z
    }
    uniforms.axes.value = axes
    this.endPoint = end
    uniforms.time.value = this.min
    if (this.max < this.min) {
      const temp = this.max
      this.max = this.min
      this.min  = temp
      invert = 1
      this.endPoint = start
      uniforms.time.value = this.max
    }
    uniforms.invert.value = invert
  }

  initMaterial() {
    const material = new ShaderMaterial({
      uniforms: this.uniforms,
      vertexShader,
      fragmentShader,
      transparent: true,
      // blending: AdditiveBlending,
      depthTest: true,
    })
    return material
  }

  initPointMesh() {
    const geometry = new BufferGeometry()
    geometry.setFromPoints(this.points)
    this.pointMesh = new Points(geometry, this.material)
  }

  disposed() {
    this.state = false
    this.material.dispose()
    this.pointMesh.geometry.dispose()
    this.material = null
    this.uniforms = null
    if (this.afterDispose && this.afterDispose instanceof Function) {
      this.afterDispose(this)
    }
  }

  update() {
    if (!this.state) return
    const time = this.uniforms.time.value
    const size = this.uniforms.size.value
    const invert = this.uniforms.invert.value
    // console.log('----------',invert);
    if (invert) {
      if (time < this.minx) {
        if (this.loop) {
          this.uniforms.time.value = this.maxx + size
        } else {
          this.disposed()
          return
        }
      }
      this.uniforms.time.value -= this.speed

      if (time < this.min) {
        if (this.loop) {
          this.uniforms.time.value = this.max + size
        } else {
          this.disposed()
          return
        }
      }
      this.uniforms.time.value -= this.speed
    } else {
      if (time > this.max) {
        if (this.loop) {
          this.uniforms.time.value = this.min - size
        } else {
          this.disposed()
          return
        }
      }
      this.uniforms.time.value += this.speed
    }
  }
}
